definitions:
  domain.SignIn:
    properties:
      address:
        description: |-
          Login    string `json:"login" binding:"required"`
          Password string `json:"password" binding:"required"`
        type: string
      fio:
        type: string
      phonenumber:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for WebConst
  title: WebConst_BackEnd
  version: dev
paths:
  /auth/sign-in:
    post:
      consumes:
      - application/json
      description: login
      operationId: user-login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.SignIn'
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - auth
swagger: "2.0"
